# -*- coding: utf-8 -*-
"""atividade_do_imposto.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ukXZgYNbOZ7-3doFXxC5rQaHb5TK8nr-
"""

try:
    salario = float(input('Qual o seu salário? '))
    if salario <= 1302.01:
        print('Contribuente isento do INSS')
    elif 1302.02 >= salario:
        print(f'Terá que pagar R$ {(salario * 7.5) / 100:.2f} de INSS')
    elif 1302.02 < salario <= 2571.29:
        print(f'Terá que pagar R$ { (salario * 12) / 100:.2f} de INSS')
    elif 2571.30 < salario <= 3856.94:
        print(f'Terá que pagar R$ { (salario * 12) / 100:.2f} de INSS')
    elif 3856.95 < salario < 7507.49:
        print(f'Se deu mal, paga pro governo R$ {(salario * 14) / 100} de INSS')
except:
  print('Digite um salário válido.')

try:
    salario = float(input('Qual o seu salário? '))
    if salario < 1903.98:
        print('Contribuente isento de imposto de renda')
    elif salario >= 1903.99 and salario <= 2826.65:
        if (salario * 0.075) >= 142.80:
          print(( (f'O salário é R$ {salario - 142.80}, descontando R$ 142.80') ))
        else:
          print('O salário é R$  ',round(salario - (salario * 0.075),2),', descontando R$', round(  (salario * 0.075),2  )  )

    elif salario >= 2826.66 and salario <= 3751.05:
      if (salario * 0.15) >= 354.80:
        print('O salário é R$',(salario - 354.80),', descontando R$ 354.80')
      else:
        print ('O salário é R$  ',round(salario - (salario * 0.15),2),', descontando R$', round(  (salario * 0.15),2  )  )

    elif salario >= 3751.06 and salario <= 4664.68:
        if ((salario * 0.25)>= 636.13):
          print('O salário é R$',(salario - 636.13),',descontando R$ 636.13')
        else:
          print('O salário é R$  ',round(salario - (salario * 0.25),2),', descontando R$ 636,13')

    elif salario >= 4664.69:
        if((salario * 0.27) >= 869.36):
          print('O salário é R$',(salario - 869.36),'descontando R$ 869.36')
        else:
          print('O salário é R$  ',round(salario - (salario * 0.27),2),', descontando R$', round(  (salario * 0.027),2  )  )
except:
  print('Digite um salário válido.')